# Generated by Django 2.2.4 on 2023-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
